// 15 text/fact questions (same spirit as your Tk app)
window.TEXT_QUESTIONS = [
  {type:"text", q:"Which sentence is AI-generated?",
    options:[
      "I can’t start my day without coffee, or at least the idea of it.",
      "Morning routines are optimized through the ingestion of caffeinated liquid substances."
    ], answer:1, diff:"Easy"},
  {type:"fact", q:"Which fact is true?",
    options:["The first chatbot was built in the 1960s","Siri was the first AI ever invented","ChatGPT once ran for political office in Sweden"],
    answer:0, diff:"Easy"},
  {type:"text", q:"Which joke was AI-written?",
    options:["I told my plants a joke today. They didn’t laugh, but they did look a little greener.","Why did the algorithm cross the road? To optimize the chicken’s trajectory."],
    answer:1, diff:"Easy"},
  {type:"text", q:"Which short diary note is AI?",
    options:["Got caught in the rain today. Soaked, but the puddles made the city sparkle.","Rainfall created hydration-based reflections on urban infrastructure."],
    answer:1, diff:"Easy"},
  {type:"fact", q:"Which of these is a common AI myth?",
    options:["AI has creativity but no consciousness","AI can directly read human thoughts","AI is trained using data"],
    answer:1, diff:"Medium"},
  {type:"text", q:"Which reflection is AI?",
    options:["Happiness isn’t something you chase, it’s something you notice when you slow down.","Happiness is a conceptual construct representing positive affective states resulting from the absence of unmet needs."],
    answer:1, diff:"Medium"},
  {type:"odd", q:"Two are real headlines. One is AI-generated. Which one?",
    options:["City zoo introduces yoga sessions with goats","Local government announces empathy algorithm for better traffic control","Town bakery launches midnight doughnut festival"],
    answer:1, diff:"Medium"},
  {type:"fact", q:"Which claim is false?",
    options:["AI models have generated fake research papers that fooled journals","AI was used to predict protein structures in biology","AI successfully cloned a living woolly mammoth"],
    answer:2, diff:"Medium"},
  {type:"text", q:"Which answer is AI?  —  What does freedom mean?",
    options:["It’s when no one can tell you who to love, where to go, or what to dream.","Freedom represents a socio-political construct enabling individuals to function without undue systemic constraints."],
    answer:1, diff:"Hard"},
  {type:"poem", q:"Odd one out: which poem is AI-generated?",
    options:["Leaves drift, the streetlamp hums / Autumn sighs, the city listens.","The arboreal structures perform cyclical chromatic alterations within seasonal frameworks.","Rain taps windows soft as breath / A lullaby for restless thoughts."],
    answer:1, diff:"Hard"},
  {type:"fact", q:"Which statement is true?",
    options:["AI has been officially named on patents in some countries","AI is banned worldwide from use in medicine","AI is legally required to pay taxes in Japan"],
    answer:0, diff:"Hard"},
  {type:"text", q:"Which short review was AI?",
    options:["The pizza was warm, cheesy, and the crust reminded me of home.","The culinary product delivered satisfactory sensory metrics, especially in carbohydrate structure.","Honestly, too salty. Wouldn’t order again."],
    answer:1, diff:"Hard"},
  {type:"text", q:"Which reflection is AI?",
    options:["Losing is bitter, but it makes the next win taste like honey.","Loss represents a negative performance metric enhancing the contrastive value of future achievements."],
    answer:1, diff:"Hard"},
  {type:"text", q:"Which one is AI-generated?",
    options:["Democracy survives not through perfection but through imperfection shared by many.","Democracy is a governance structure facilitating distributed consensus among heterogeneous populations.","Both A and B are AI"],
    answer:1, diff:"Hard"},
  {type:"text", q:"Which of these is the AI response? — What does love feel like?",
    options:["It’s like a fire in your chest and a whisper in your bones.","Love is an emergent affective phenomenon characterized by neurochemical interactions producing attachment behaviors."],
    answer:1, diff:"Final"}
];
